site_name: V1nci 的笔记本
site_url: https://note.v1nci.xyz/
repo_name: coldinke/notebook
repo_url: https://github.com/coldinke/notebook/
edit_uri: tree/main/docs
site_description: V1nci 的笔记本
copyright: Copyright &copy; 2024 <a href="https://github.com/coldinke" target="_blank" rel="noopener">V1nci</a>

theme:
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/abugida-devanagari
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false
  palette:
    - scheme: default

markdown_extensions:
  - toc
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox:  true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - css/custom_color.css


nav:
  - Home:
    - index.md
  - CS:
    - cs/index.md
  - Tools:
    - tools/index.md
    - Linux 常用工具:
      - 文件相关: tools/common.md
      - 网络相关: tools/network.md
      - 系统监测: tools/monitoring.md
    - 开发中常用工具:
      - Git: tools/Git.md
    - 包管理器:
      - 汇总: tools/package.md